### ISSUE TITLE
Bug With Groups

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-sdk-python#101]
Hey all,

We've got a serious issue here, which is blowing up customer apps. We need to get this fixed ASAP and add in some regression tests to ensure this doesn't pop up in the future.

I've only tested this issue on Groups, but I'm assuming this will also cause errors for any list resources.

Here's how you can reproduce this using the latest stable library release:

```
>>> from stormpath.client import Client
>>> client = Client(api_key_file_location='/Users/rdegges/Downloads/rdegges.properties')
>>> app = client.applications.search('test')[0]  # I've got an app named 'test' I'm using here.
>>> for group in app.groups.search('group'):  # I created 1,000 groups named: group1, group2, ..., groupN
...  print group.name
group0
group1
group10
group100
group101
group102
group103
group104
group105
group106
group107
group108
group109
group11
group110
group111
group112
group113
group114
group115
group116
group117
group118
group119
group12
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rdegges/.virtualenvs/python/lib/python2.7/site-packages/stormpath/resources/base.py", line 361, in __iter__
    items = self._get_next_page(offset, limit)
  File "/Users/rdegges/.virtualenvs/python/lib/python2.7/site-packages/stormpath/resources/base.py", line 336, in _get_next_page
    data = self._store.get_resource(self.href, params=params)
  File "/Users/rdegges/.virtualenvs/python/lib/python2.7/site-packages/stormpath/data_store.py", line 122, in get_resource
    data = self.executor.get(href, params=params)
  File "/Users/rdegges/.virtualenvs/python/lib/python2.7/site-packages/stormpath/http.py", line 91, in get
    return self.request('GET', url, params=params)
  File "/Users/rdegges/.virtualenvs/python/lib/python2.7/site-packages/stormpath/http.py", line 81, in request
    raise Error(r.json(), http_status=r.status_code)
stormpath.error.Error: Authentication with a valid API Key is required.
```

It seems I'm 100% unable to iterate over searched collections.

After I run the above search, my client is left in a broken state -- I'm unable to make any other requests as it complains about authentication :(

**Comment by rdegges** [comment]
Perfectly working.
