### ISSUE TITLE
Gevent + Stormpath = :(

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-sdk-python#164]
Heyo!

So... At one point a while back I built this tool to 'seed' Stormpath accounts: https://github.com/rdegges/stormpath-seed

I was just doing some maintenance work on it and realized I'm getting super odd errors.

After debugging for a bit, I realized that our current version of the python sdk is breaking gevent compatibility.

Here's a reproduction example:

```python
# pip install -U gevent stormpath
from gevent.monkey import patch_all
patch_all()

from stormpath.client import Client

client = Client(id='xxx', secret='yyy')
for app in client.applications:
    print app.name
```

The above example errors out with:

```python
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    for app in client.applications:
  File "/Users/rdegges/.virtualenvs/python-debug/lib/python2.7/site-packages/stormpath/client.py", line 72, in applications
    return self.tenant.applications
  File "/Users/rdegges/.virtualenvs/python-debug/lib/python2.7/site-packages/stormpath/resources/base.py", line 98, in __getattr__
    self._ensure_data()
  File "/Users/rdegges/.virtualenvs/python-debug/lib/python2.7/site-packages/stormpath/resources/base.py", line 227, in _ensure_data
    data = self._store.get_resource(self.href, params=params)
  File "/Users/rdegges/.virtualenvs/python-debug/lib/python2.7/site-packages/stormpath/data_store.py", line 139, in get_resource
    data = self.executor.get(href, params=params)
  File "/Users/rdegges/.virtualenvs/python-debug/lib/python2.7/site-packages/stormpath/http.py", line 177, in get
    return self.request('GET', url, params=params)
  File "/Users/rdegges/.virtualenvs/python-debug/lib/python2.7/site-packages/stormpath/http.py", line 155, in request
    raise Error({'developerMessage': str(e)})
stormpath.error.Error: __init__() got an unexpected keyword argument 'server_hostname'
```

I can verify that this *was* previously working back in 1.3.6 -- so something must have changed since then.

@avojnovicDk I'd love it if you could take a look into this!

I know from previous customer meetings that we have quite a few people using gevent in their apps, and if this is causing breakage it might bubble up to some bad issues for our users :(

Thanks!!!

**Comment by senko** [comment]
Looks like this might be urllib3 + gevent breakage: https://github.com/shazow/urllib3/issues/482

**Comment by avojnovicDk** [comment]
Hey, @rdegges ! I tried with latest Stormpath and Gevent versions, but I couldn't reproduce this. Also, I upgraded Python from 2.7.5 to 2.7.9, and it still works. Can you tell me which versions of Python, Stormpath and Gevent are you using?

**Comment by rdegges** [comment]
Closing this as it is fixed.

Thanks @senko and @avojnovicDk for all the helps ^^
