### ISSUE TITLE
Unable to Iterate Through Account Store Mappings

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-sdk-python#171]
It looks like it's currently impossible to iterate over account store mappings from the Client, eg:

```python
>>> client = Client(id='xxx', secret='yyy')
>>> for x in client.account_store_mappings: print x
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rdegges/.virtualenvs/stormpath-export/lib/python2.7/site-packages/stormpath/resources/base.py", line 383, in __iter__
    self._ensure_data()
  File "/Users/rdegges/.virtualenvs/stormpath-export/lib/python2.7/site-packages/stormpath/resources/base.py", line 227, in _ensure_data
    data = self._store.get_resource(self.href, params=params)
  File "/Users/rdegges/.virtualenvs/stormpath-export/lib/python2.7/site-packages/stormpath/data_store.py", line 139, in get_resource
    data = self.executor.get(href, params=params)
  File "/Users/rdegges/.virtualenvs/stormpath-export/lib/python2.7/site-packages/stormpath/http.py", line 177, in get
    return self.request('GET', url, params=params)
  File "/Users/rdegges/.virtualenvs/stormpath-export/lib/python2.7/site-packages/stormpath/http.py", line 172, in request
    self.raise_error(r)
  File "/Users/rdegges/.virtualenvs/stormpath-export/lib/python2.7/site-packages/stormpath/http.py", line 125, in raise_error
    raise Error({'developerMessage': ret}, http_status=r.status_code)
stormpath.error.Error: {u'status': 405, u'developerMessage': u"Request method 'GET' not supported", u'message': u"Request method 'GET' not supported", u'code': 405, u'moreInfo': u'mailto:support@stormpath.com'}
```

Would you take a look at this, @avojnovicDk ? Thanks!

**Comment by avojnovicDk** [comment]
@rdegges, seems like there is no way to get account store mappings from the Client. As documented in http://docs.stormpath.com/rest/product-guide/#account-store-mappings, you cannot call GET on /v1/accountStoreMappings/. POST and DELETE are supported, and so is GET on /v1/accountStoreMappings/:accountStoreMappingId .
Strangely, there is account_store_mappings property on the Client in the Python SDK, but, as you reported, it doesn't work. Right now, it seems that I should remove it. What do you think?

**Comment by senko** [comment]
@avojnovicDk I assume the `account_store_mappings` property on `Client` works for creating, deleting, and accessing a particular account store mapping? If so, the property is still useful although listing is not available.

In that case it may be better to just disallow iteration through that particular resource.

**Comment by avojnovicDk** [comment]
Right, I should only raise an error in that case! Thanks, @senko!

**Comment by rdegges** [comment]
Thanks @senko and @avojnovicDk. This makes sense -- did not realize this was a limitation of the API. I think disallowing iteration would be an appropriate solution =)

Would you also add in a test case for that as well? Thanks!
