### ISSUE TITLE
Client.groups Not Working

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-sdk-python#216]
It appears that I'm unable to iterate through `client.groups`. This functionality should be working, but results in a 404:

```python
>>> from stormpath.client import Client
>>> client = Client(id='xxx', secret='xxx+fTcs')
>>> for group in client.groups:
...  print group.href
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rdegges/.virtualenvs/migrate/lib/python2.7/site-packages/stormpath-2.1.1-py2.7.egg/stormpath/resources/base.py", line 405, in __iter__
    self._ensure_data()
  File "/Users/rdegges/.virtualenvs/migrate/lib/python2.7/site-packages/stormpath-2.1.1-py2.7.egg/stormpath/resources/base.py", line 248, in _ensure_data
    data = self._store.get_resource(self.href, params=params)
  File "/Users/rdegges/.virtualenvs/migrate/lib/python2.7/site-packages/stormpath-2.1.1-py2.7.egg/stormpath/data_store.py", line 139, in get_resource
    data = self.executor.get(href, params=params)
  File "/Users/rdegges/.virtualenvs/migrate/lib/python2.7/site-packages/stormpath-2.1.1-py2.7.egg/stormpath/http.py", line 177, in get
    return self.request('GET', url, params=params)
  File "/Users/rdegges/.virtualenvs/migrate/lib/python2.7/site-packages/stormpath-2.1.1-py2.7.egg/stormpath/http.py", line 172, in request
    self.raise_error(r)
  File "/Users/rdegges/.virtualenvs/migrate/lib/python2.7/site-packages/stormpath-2.1.1-py2.7.egg/stormpath/http.py", line 125, in raise_error
    raise Error({'developerMessage': ret}, http_status=r.status_code)
stormpath.error.Error: {u'status': 404, u'developerMessage': u'The requested resource does not exist.', u'message': u'The requested resource does not exist.', u'code': 404, u'moreInfo': u'mailto:support@stormpath.com'}
```

@avojnovicDk would you look into this?

**Comment by avojnovicDk** [comment]
@rdegges, are you sure this should be working? It seems to me that this should raise an error, because GET and POST methods are not available on /groups endpoint. I made PR to raise an error in these cases: #217 .

**Comment by rdegges** [comment]
Closing as I merged in the PR so we'll throw a custom error. Thanks @avojnovicDk for looking into this.
